실제 운영 환경처럼 설정

3계층 아키텍처 - 개발환경
namespace: prod
웹 및 톰캣은 부하분산이 가능하게 설정
리소스 쿼터 운영환경


- 네임스페이스 설정
- db시크릿키
- db pv pvc
- was 서버 설정파일
- was pv pvc
- web 서버 설정파일
- wes pv pvc


pod 부하분산일경우 
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-memory
db
was
web


3계층 아키텍처 - 개발환경
namespace: dev
웹 및 톰캣은 부하분산이 가능하게 설정
리소스 쿼터 개발환경

모니터링시스템
namespace: monitoring


---
# dev 네임스페이스 셋팅

#네임스페이스 선언
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  nodeSelecter:
    kubernetes.io/hostname: node2
---

#db 설정파일
apiVersion: v1
kind: Secret
metadata:
  namespace: dev
  name: sec-mysql
data:
  MYSQL_ROOT_PASSWORD: cXdlcjEyMzQ=  #qwer1234 를 base64 인코딩한값


---

#was 설정파일
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: cm-was
data:
  TYPE: '0.0.0.0'

---

#web 설정파일

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev
  name: cm-httpd
data:
  TYPE: 'svc-was'

---


#PV생성 (mysql)
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: mysql-pv-dev
spec:
  capacity:
    storage: 5G #용량2기가
  accessModes:
  - ReadWriteOnce
  local: #지금은 로컬에 연결 각종타입이 지원됨
    path: /3tir/mysql #디렉토리를 생성해둬야함
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [node2]}

---

#PVC 로 PV연동
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: mysql-pvc-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: ""

---

apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: mysql-server
  labels:
     app: db-pod
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    envFrom:
    - secretRef:
        name: sec-mysql  #mysql 설정파일을 불러오자
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-pvc-pv-dev
  volumes:
  - name : mysql-pvc-pv-dev
    persistentVolumeClaim:
      claimName: mysql-pvc-dev


---

#mysql 서비스 생성
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: svc-mysql
spec:
  selector:
    app: db-pod
  ports:
  - port: 3306
    containerPort: 3306



---
---
#db 생성 끝
---
---


---
---
#was 생성 시작
---
---



---
#was pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: pv-was-dev
spec:
  capacity:
    storage: 1G #용량1기가
  accessModes:
  - ReadWriteOnce
  local: #지금은 로컬에 연결 각종타입이 지원됨
    path: /3tir/was #디렉토리를 생성해둬야함
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [node2]}

---
#was pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: pvc-was-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: ""


---
#was pod
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: was-deploy-dev
spec:
  selector:
    matchLabels:
      servertype: was-cpu-dev
  replicas: 2
  template:
    metadata:
      labels:
        servertype: was-cpu-dev
    spec:
      containers:
      - name: was
        image: yoskr/tomcat:1.1
        envFrom:
        - configMapRef:
            name: cm-was  #cm-dev 설정파일을 불러오자
        ports:
        - containerPort: 8009
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps
          name: was-pvc-pv-dev
          requests:
            cpu: 100m
          limits:
            cpu: 200m
      volumes:
      - name : was-pvc-pv-dev
        persistentVolumeClaim:
          claimName: pvc-was-dev

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: dev
  name: hpa-was-cpu-dev
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was-deploy-dev
  metrics:
  - type: Resource 
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---

apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: svc-was
spec:
  selector:
    servertype: was-cpu-dev
  ports:
  - name: live
    port: 8009
    containerPort: 8009
---
---
#was 생성 끝
---
---



---
---
#web 생성 시작
---
---

---
#web pv
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: pv-web-dev
spec:
  capacity:
    storage: 1G #용량2기가
  accessModes:
  - ReadWriteOnce
  local: #지금은 로컬에 연결 각종타입이 지원됨
    path: /3tir/web
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [node2]}

---
#web pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: pvc-web-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: ""
---
#web pod



apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: web-deploy-dev
spec:
  selector:
    matchLabels:
      servertype: web-cpu-dev
  replicas: 2
  template:
    metadata:
      labels:
        servertype: web-cpu-dev
    spec:
      containers:
      - name: web
        image: yoskr/httpd:0.4
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: cm-httpd  #cm-httpd 설정파일을 불러오자
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: web-pvc-pv-dev
      volumes:
      - name : web-pvc-pv-dev
        persistentVolumeClaim:
          claimName: pvc-web-dev

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: dev
  name: hpa-web-cpu-dev
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deploy-dev
  metrics:
  - type: Resource 
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: svc-web-dev
spec:
  selector:
    servertype: web-cpu-dev
  ports:
  - port: 80 # 사용자들이 접속할 포트
    targetPort: 80 # 파드의 포트번호
  type: LoadBalancer