#파드 API
apiVersion: #v1 설정
kind: #오브젝트를 지정
metadata : #오브젝트의 정보를 입력, name은 필수, 
spec : 
  initContainers : #초기화 전용 컨테이너의 명세를 기술
  nodeSelector : #파드가 배포될 노드를 지정
    kubernetes.io/hostname: #노드 이름 지정
  volumes : #파드 내 컨테이너 간에 공유할 수 있는 볼륨을 지정
  containers : #컨테이너의 명세를 배열로 기술
    image : #컨테이너 생성시 사용할 이미지
    name : #컨테이너 이름
    livenessProbe : #컨테이너 내의 프로그램이 정상적으로 동작 중인지 검사하는 프로브
    readinessProbe : #컨테이너 내의 프로그램이 사용자의 요청을 받을 준비가 되었는지 검사하는 프로브
    ports : #외부 요청을 전달하기 위한 포트 목록, 배열로 작성
      containerPort : #포트 번호 지정
    resources : #CPU와 메모리 제한
    volumeMounts : #파드에 정의한 볼륨을 컨테이너의 마운트할 경로
    command : #컨테이너 생성 시 마지막에 실행할 명령어
    args : #command의 매개변수
    env : #환경변수 설정
